server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GC-HeyKakao/HeyForm-Config.git
          username: parkchanbin54
          password: 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
          default-label: main
          ignore-local-ssh-settings: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
